### ISSUE TITLE
White spaces in character strings

### ISSUE THREAD

**Issue by slarge** [ices-tools-prod/icesDatras#2]
When getting the data, the character variables include white spaces. For example gear becomes “GOV     “ instead of “GOV”. If you would include hauldata<-as.data.frame(apply(hauldata,2,function (x) sub("\\s+$", "", x))) this issue is solved. It might also be possible to include that in the getDatras function. Then it should be solved for all selections. Communicated to me from Ralf van Hal @ralfvh

**Comment by colinpmillar** [comment]
I have fixed a similar problem in the web service output in the ```getSurveyList()``` output:
```r
  out <- gsub("[[:space:]]*$", "", out $ Survey)
```
As one of the surveys has white space at the end...
I will add to the getHHdata function, but it would be better to work on the output from the web service rather than patching things here.
