### ISSUE TITLE
getCatchWgt example slightly broken?

### ISSUE THREAD

**Issue by arnima-github** [ices-tools-prod/icesDatras#22]
The example on the getCatchWgt help page looks slightly odd. The line
`aphia <- icesVocab::findAphia(c("cod", "haddock"))`
returns only haddock codes and nothing for cod. The purpose of the example seems to be to bring in more than one species, so it could be improved.

So it may be enough to just change the example, but also look into why the current example only returns one species and not two.

**Comment by colinpmillar** [comment]
``` R
icesVocab::findAphia(c("cod", "haddock"), full = TRUE)
```
```
       Key              Description LongDescription                Modified Deprecated
138 126436             Gadus morhua             Cod 2017-01-06T11:20:09.887      false
139 126437 Melanogrammus aeglefinus         Haddock 2017-01-06T11:20:09.887      false
```
