### ISSUE TITLE
Aphia codes

### ISSUE THREAD

**Issue by James-Thorson** [ices-tools-prod/icesDatras#23]
Hi all,

I developed `FishData::download_datras` to download catch in weight from DATRAS and am happy to see that it will not be needed much longer.

I had previously used `data( aphia, package="icesDatras" )` to bring into memory the data-frame used to match the Aphia code to genus-species latin binomials.  Is this data-package still available somewhere, or in the version-control history?  

It would simplify things somewhat for my short-term goals if I could just obtain that one file and load it with `FishData` for now.

Jim

**Comment by ha0ye** [comment]
Looks like this got shunted off into `icesVocab::findAphia()` as part of merge #25

**Comment by James-Thorson** [comment]
you willing to do a pull request to fix this?

**Comment by ha0ye** [comment]
I'll take a look over the weekend. It's a bit more than the 5 minute fix I originally thought it might be.

**Comment by colinpmillar** [comment]
Sorry - forgot about this one!

you can use this:
``` R
icesVocab::getCodeList("SpecWoRMS")
```
```
       Key                 Description               LongDescription                Modified Deprecated
1   101167                    Lampetra                               2016-11-04T14:59:14.107      false
2   101170            Myxine glutinosa                               2013-11-27T14:44:29.090      false
.
.
.
187 126821        Trachurus picturatus            Blue jack mackerel 2017-01-06T11:20:09.887      false
188 126822         Trachurus trachurus                Horse mackerel 2017-01-06T11:20:09.887      false
```

The Key is the aphia code.

The icesVocab package is a link to the webservices of the ICES Reference Codes database: https://vocab.ices.dk/

I will double check with @vaishav how is the DATRAS database developer if there is anything else we need to consider.

Sorry for the delay on this one!
