### ISSUE TITLE
Installing an old version of icesDatras

### ISSUE THREAD

**Issue by afredstonhermann** [ices-tools-prod/icesDatras#27]
Thank you for developing this set of fantastic resources for accessing DATRAS. I am trying to install another R package, FishData, that relies on icesDatras, but was built for an older version of the package--see here for details: https://github.com/James-Thorson/FishData/issues/16

The FishData package relies on icesDatras version "1.1=1", which is not archived on CRAN. Do you have any suggestions for reverting to that version of icesDatras so FishData will work?

**Comment by colinpmillar** [comment]
Hi Alexa,

sorry this is very late!  you can install pervious versions directly from gthub, if you look here:
https://github.com/ices-tools-prod/icesDatras/releases

you can see the previous github releases,  then to install this you use the remotes package:

```r
remotes::install_github("ices-tools-prod/icesDatras@1.1-1")
```

hope this is still helpful!
