### ISSUE TITLE
a webservice bug to be fixed in icesDatras

### ISSUE THREAD

**Issue by einarhjorleifsson** [ices-tools-prod/icesDatras#28]
```
https://datras.ices.dk/WebServices/DATRASWebService.asmx/getHLdata?survey=NS-IBTS&year=1997&quarter=4
```
returns as the last variable in the first record: ```<Valid_Aphia/>```. which then becomes the variable name for that survey, year and quarter. in the ```icesDatras:::parseDatras``` function. but then creates problems downstream if one is reading in more than one year/quarter.

i made a temporary fix in my repo (see: https://github.com/einarhjorleifsson/icesDatras/commit/d6fc8dcf42d77ec36883dc0b8baa160386a4efc5) which you may want to consider/incorporate in one way or another

e

**Comment by colinpmillar** [comment]
Thanks! I will try and fix this week – thanks for the heads up!

**Comment by einarhjorleifsson** [comment]
i guess this should really be fixed upstream, in the webserver code.
e

**Comment by colinpmillar** [comment]
HI,

I fixed it by parsing for `<feild />` and converting to `<feild> NA </feild>`  which I hope should fix it for other missing fields.

https://github.com/ices-tools-prod/icesDatras/commit/1534670184fab4eb6f4ddab8ad0e5bbaaadec496

Thanks for the bug report!
