### ISSUE TITLE
AreaCode format issue

### ISSUE THREAD

**Issue by ClumpusJim** [ices-tools-prod/icesDatras#30]
When downloading DATRAS data, when AreaCode contains an "E" e.g. 44E3, it is converted to numeric thus displayed as 44000. Is there a way to prevent this? 

Code used 
getDATRAS(record = "CA", "SWC-IBTS", seq(1990,2010, by=1), quarters = c(1,4))

**Comment by colinpmillar** [comment]
thanks,
even just this will do it:
```r
x <- icesDatras::getDATRAS(record = "CA", "SWC-IBTS", 1990, quarters = 1)
```

It is because all stat recs are of the form xxEx  so are being interpreted as numeric - I will hard code the type into the column and that should fix it

**Comment by ClumpusJim** [comment]
Some values are now being displayed in scientific format but the column is still in integer format. New values have also appeared e.g.(1, 2, ,5 , 6, 7, 8)

x <- icesDatras::getDATRAS(record = "CA", "SWC-IBTS", 1990, quarters = 1)
table(x$AreaCode)

**Comment by colinpmillar** [comment]
should be fixed in:
https://github.com/ices-tools-prod/icesDatras/commit/1d2c16b151c04eb56a00f4dc8efd0446198b1035

Thanks!

Please download icesDatras from the master branch - we will push to CRAN later this month
```r
remotes::install_github("ices-tools-prod/icesDatras")
```

**Comment by davidcurrie2001** [comment]
Hi @colinpmillar did this fix ever get pushed to CRAN?  I am running into this problem and I noticed the source code on CRAN doesn't seem to have your fix included.  If I install the package from GitHub the stat rectangles remain as text, but using the CRAN package they are sometimes converted to numbers (if all rectangles in the downloaded data are in the format nnEn).
