### ISSUE TITLE
Downloaded package with install_github("ices-tools-prod/icesDatras") gets a corrupt package

### ISSUE THREAD

**Issue by Franvgls** [ices-tools-prod/icesDatras#39]
have installed the package, previously had it installed from CRAN and worked but limited to the download hh, hl and ca records.
I get an error: 
Error in fetch(key) : 
  lazy-load database 'D:/FVG/R/win-library/3.6/icesDatras/help/icesDatras.rdb' is corrupt
I find several instances of the icesDatras.rbd files in temp folders and user libraries of R.3.6 (do not use R.4 cause have problems to use 64 bits versions and the RODBC libraries ....
Well, in any case any hint on what is going wrong?
Thanks in advance.

**Comment by colinpmillar** [comment]
Hi Fran,
I don;t know what could be causing this problem, it may be related to this issue raised in the devtools package github:

https://github.com/r-lib/devtools/issues/419

**Comment by Franvgls** [comment]
Hi Colin, thanks for your quick reply! Luckily it looks like it's solved, yesterday I uninstalled the icesDatras version and reinstalled the one from github, it gave the same error, but this morning when I opened the icesDatras package it worked and had the new functions to get catches and indices (still trying them, but looks like they work). 
But can't offer any hint on how it was solved apart from the usual solution: close and reboot....
Best

**Comment by colinpmillar** [comment]
great news! thanks for letting me know :)  yes, turn it off and on again is a classic solution
