### ISSUE TITLE
Release to CRAN?

### ISSUE THREAD

**Issue by davidcurrie2001** [ices-tools-prod/icesDatras#40]
Hi,
Can a newer version of the code be released to CRAN in the near future?  The current version available on CRAN has a number of bugs which have been fixed in the code on GitHub (e.g. wrongly converting nnEn rectangles to numbers #30 ) - guiding users to install from GitHub is a bit of a pain.
Thanks in advance,
Dave

**Comment by colinpmillar** [comment]
version 1.4.0 On its way to CRAN
