### ISSUE TITLE
getDATRAS for HL 

### ISSUE THREAD

**Issue by AndyCampbell** [ices-tools-prod/icesDatras#41]
icesDatras::getDATRAS(record="HL", survey="SWC-IBTS", years=c(1986,1987), quarters=1)

returns the error
Error in match.names(clabs, names(xi)) : 
  names do not match previous names

doesn't occur for "HH" records nor for "HL" if separate calls are made for each of 1986 and 1987

**Comment by colinpmillar** [comment]
Hi, sorry for the slow response, it seems to be fixed now unless you can recreate?

icesDatras updates are on thier way to CRAN
