### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by slarge** [ices-tools-prod/icesDatras#7]
It might be useful to have a citation function for all data packages - not for the packages, but for the data. 
e.g., `dataCitation(getDatras())`

![image](https://cloud.githubusercontent.com/assets/5000131/18625054/3da48e64-7e4c-11e6-9a99-d93fdc1f04d1.png)

**Comment by colinpmillar** [comment]
transferred to https://github.com/ices-taf/doc/issues/261
